services:
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    AkeneoDAMConnector\Infrastructure\DAM\Bynder\:
        resource: '../../src/Infrastructure/DAM/Bynder/*'

    AkeneoDAMConnector\Infrastructure\Bynder\ClientBuilder:
        arguments:
            $consumerKey: '%env(BYNDER_CONSUMER_KEY)%'
            $consumerSecret: '%env(BYNDER_CONSUMER_SECRET)%'
            $token: '%env(BYNDER_CLIENT_KEY)%'
            $tokenSecret: '%env(BYNDER_CLIENT_SECRET)%'
            $baseUrl: '%env(BYNDER_URL)%'
